###############################################################################
#                                                                             #
#  Override KVMD settings.                                                    #
#                                                                             #
#    * https://docs.pikvm.org/first_steps/#structure-of-configuration-files   #
#                                                                             #
#  This file uses YAML syntax. All overridden parameters will be applied      #
#  AFTER other configs and "!include" directives, and BEFORE validation.      #
#  Values should be combined under common sections.                           #
#                                                                             #
###############################################################################
#
#########
# Wrong #
#########
#kvmd:
#    gpio:
#        drivers: ...
#kvmd:
#    gpio:
#        scheme: ...
#
###########
# Correct #
###########
#kvmd:
#    gpio:
#        drivers: ...
#        scheme: ...
#
###########
# Example #
###########
#vnc:
#    # See https://docs.pikvm.org/vnc
#    keymap: /usr/share/kvmd/keymaps/ru # Set russian keymap
#    auth:
#        vncauth:
#            enabled: true # Enable auth via /etc/kvmd/vncpasswd

webrtc:
    type: live777
    port: 7777
    stun:
        host: stun.l.google.com
        port: 19302
    memsink:
        h264:
            sink: "kvmd::ustreamer::h264"
        audio:
            capture:
                device: "hw:tc358743,0"
            playback:
                device: "plughw:UAC2Gadget,0"

# Disable janus if it was enabled
janus:
    enabled: false
